apiVersion: v1
kind: Pod
metadata:
  labels:
    jenkins: jenkins-pipeline
spec:
  serviceAccountName: svc-jenkins
  securityContext:
    runAsUser: 0
  volumes:
    - name: dind-storage
      emptyDir: {}
  containers:
    - name: jnlp
      image: jenkins/jnlp-slave:latest
      resources:
        requests:
          memory: "100Mi"
          cpu: "100m"
        limits:
          memory: "1000Mi"
          cpu: "1000m"
    - name: utilities
      image: dind-aws-helm:latest
      securityContext:
        privileged: true
      volumeMounts:
        - name: dind-storage
          mountPath: /var/lib/docker
      resources:
        requests:
          memory: "100Mi"
          cpu: "100m"
        limits:
          memory: "1000Mi"
          cpu: "1000m"