apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  name: {{ .Values.serviceAccountName }}