# Default values for helm-charts.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 2
restartPolicy: Always
serviceAccountName: svc-sampleapp
image:
  repository: 670053613788.dkr.ecr.us-east-1.amazonaws.com/sample
  tag: latest
  pullPolicy: Always

appName: sampleapp

service:
  type: ClusterIP
  port: 8080
  targetPort: 8080
  protocol: TCP
  name: samplesvc

container:
  name: http
  port: 8080
  protocol: TCP

resources:
  requests:
    cpu: 200m
    memory: 256Mi
  limits:
    cpu: 250m
    memory: 1024Mi