apiVersion: v1
kind: Service
metadata:
  name: {{ template "jenkins-k8s.fullname" . }}
  labels:
    app: {{ template "jenkins-k8s.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  annotations:
  #   service.beta.kubernetes.io/aws-load-balancer-security-groups: "sg-0735c28534da74bfe"
    service.beta.kubernetes.io/aws-load-balancer-extra-security-groups: "sg-03c5efba88662666d"
spec:
  type: {{ .Values.service.type }}
{{- if .Values.service.loadBalancerSourceRanges }}
  loadBalancerSourceRanges:
{{ toYaml .Values.service.loadBalancerSourceRanges | indent 4 }}
{{- end }}
  ports:
    - port: {{ .Values.service.externalPort }}
      targetPort: {{ .Values.service.internalPort }}
      protocol: TCP
      name: http
  selector:
    app: {{ template "jenkins-k8s.name" . }}
    release: {{ .Release.Name }}
